services:
  postgres:
    image: postgres:latest
    build: ./cook4u-development-environment/postgres
    environment:
      POSTGRES_USER: "useradmin"
      POSTGRES_PASSWORD: "useradmin"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/pgsql/data
      - ./cook4u-development-environment/postgres/postgresql-data/:/opt/app-root/src/postgresql-start/data
volumes:
  postgres-data: