INSERT INTO public."dishes" ("name", "description", "price", "type")
VALUES ('Bruschetta', 'Toasted bread topped with diced tomatoes, garlic, basil, and olive oil.', 8.00, 'Starter'),
       ('Spaghetti Carbonara', 'Spaghetti pasta tossed with pancetta, eggs, and parmesan cheese.', 15.00, 'Main'),
       ('Tiramisu', 'Layers of espresso-soaked ladyfingers and mascarpone cream.', 8.00, 'Dessert'),
       ('Prosciutto e Melone', 'Thinly sliced prosciutto served with fresh cantaloupe melon.', 12.00, 'Starter'),
       ('Fettuccine Alfredo', 'Fettuccine pasta in a rich cream and parmesan sauce.', 18.00, 'Main'),
       ('Cannoli', 'Crisp tubes of fried pastry filled with sweet ricotta cream and chocolate chips.', 8.00, 'Dessert'),
       ('Antipasto platter', 'Selection of cured meats, marinated vegetables, and cheeses.', 15.00, 'Starter'),
       ('Ossobuco alla Milanese', 'Slow-cooked veal shank served with saffron risotto.', 25.00, 'Main'),
       ('Panna Cotta', ' Creamy vanilla custard topped with mixed berries.', 8.00, 'Dessert'),
       ('Zuppa di Verdure', 'Vegetable soup with a variety of fresh vegetables and a touch of olive oil.', 6.00, 'Starter'),
       ('Pollo alla Parmigiana', 'Breaded chicken cutlet topped with tomato sauce and mozzarella cheese.', 20.00, 'Main'),
       ('Crostata di Frutta', 'Homemade fruit tart with a flaky pastry crust and a fruit filling.', 10.00, 'Dessert'),
       ('Cozze alla Marinara', 'Mussels cooked in a flavorful tomato sauce with garlic and white wine.', 12.00, 'Starter'),
       ('Risotto ai Funghi', 'Risotto with mushrooms, parmesan cheese, and truffle oil.', 22.00, 'Main'),
       ('Tiramisu', 'Layers of espresso-soaked ladyfingers and mascarpone cream.', 8.00, 'Dessert'),
       ('Carpaccio di Manzo', 'Thinly sliced raw beef served with arugula, parmesan cheese, and a lemon dressing.', 14.00, 'Starter'),
       ('Vitello al Marsala', 'Veal scallops sautéed with marsala wine and mushrooms.', 28.00, 'Main'),
       ('Panna Cotta', 'Creamy vanilla custard topped with mixed berries.', 8.00, 'Dessert'),
       ('Caprese', 'Fresh mozzarella, tomatoes, and basil drizzled with olive oil.', 8.00, 'Starter'),
       ('Ossobuco', 'Braised veal shanks served with risotto', 28.00, 'Main'),
       ('Cannoli', 'Crispy pastry shells filled with sweet ricotta cheese and chocolate chips.', 12.00, 'Dessert'),
       ('Bruschetta', 'Grilled bread topped with diced tomatoes, garlic, basil, and extra-virgin olive oil.', 6.00, 'Starter'),
       ('Lasagna', 'Homemade lasagna made with meat sauce, béchamel sauce, and parmesan cheese', 22.00, 'Main'),
       ('Tiramisu', 'Layers of espresso-soaked ladyfingers and mascarpone cream.', 10.00, 'Dessert'),
       ('Arancini', 'Fried risotto balls filled with mozzarella cheese.', 7.00, 'Starter'),
       ('Margherita Pizza', 'Classic pizza with tomato sauce, mozzarella cheese, and basil.', 15.00, 'Main'),
       ('Panna Cotta', 'Creamy vanilla custard topped with berry compote.', 9.00, 'Dessert');