INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES ( , 10);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 25);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 16);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 13);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 1);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 22);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 7);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 4);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 19);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 14);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 2);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 5);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 8);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 11);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 17);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 20);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 23);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 26);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 9);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 3);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (1, 21);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 6);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 27);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (2, 15);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 12);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES (3, 24);
INSERT INTO public."MenuDish" ("MenuId", "DishId") VALUES ( 3, 18);